PastaMaker-FS/PastaMaker

- .travis.yml
- package.json
Changed Name in package json and travis yml file.
---
> This is a test

- package-lock.json
- server/db/models/address.js
- server/db/models/index.js
- server/db/models/user.js
Under the db folder:
Finished User and Address models.
> finished user and address models

- package-lock.json
- server/db/models/product.js
- server/db/models/productTag.js
- server/db/models/productType.js
I created the starting Product, ProductTag and ProductType models. I created the associations between these, and the Class and Instance methods for finding Products by Tag, by Type  and finding all Tags of a product and all Types of a product.
> Product, ProductType and ProductTag + Association + Methods created.

- package-lock.json
- server/db/models/index.js
- server/db/models/item.js
- server/db/models/order.js
Added item model and item-model associations in db/model/item.js and db/model/index.js.
> Item model

- package-lock.json
- server/db/models/order.js
add order model in db/models/order.js
> added order model

- server/api/users.js
- server/db/models/address.js
- server/db/models/index.js
Updated Routes and update partial address model
> Finished user routes and upated address model

- server/api/products.js
> added single product route

- client/store/product.js
- server/api/index.js
- server/api/products.js
- server/db/models/product.spec.js
> Product Reducer Completed.

- script/seed.js
- server/api/users.js
- server/db/models/product.js
- server/db/models/productTag.js
- server/db/models/productType.js
> Order routes

- client/components/navbar.js
- package-lock.json
- package.json
> Added buttons to navbar

- client/app.js
- client/components/allProducts.js
- client/components/navbar.js
- client/routes.js
- client/store/index.js
- client/store/product.js
> Finished all products

- client/components/admin.js
- client/store/user.js
- package-lock.json
- server/db/models/address.js
Finished redux store for users. Started on admin component.
> finished user thunks/reducers

- client/app.js
- client/components/products/allProducts.js
- client/routes.js
> working on react routes

- client/components/navbar.js
- client/components/user-home.js
- client/routes.js
Updated route for initial landing page for home
> updated home page routes

- client/components/aboutus.js
- client/components/user-home.js
- client/routes.js
Updated user and admin component
> updated user and admin component

- client/app.js
- client/components/allProducts.js
- client/components/products/productGrid.js
- client/components/products/productThumb.js
- public/style.css
> Finish product grid

- client/app.js
- client/components/products/productGrid.js
- client/components/products/singleProduct.js
- public/style.css
> Component to display all the products full working. Could be refactored. 

- client/app.js
- client/components/aboutus.js
- client/components/products/productGrid.js
- client/components/products/productThumb.js
- client/routes.js
- server/api/users.js
Added some style working on Navbar to add button cart
> added flex styles

- client/components/sign-form.js
Updated sign in form. Still needs some tweaking.
> updated sign form

- server/api/index.js
fix master by removing old ref to api/items
> fix break by removing old ref to api/items

- client/components/sign-form.js
- script/seed.js
- server/api/address.js
- server/db/models/user.js
Added address dummy data to seed file. Modifying user put and post routes to eager load address data. Updating sign up form to include address fields.
> updated seed file and working on address form/routes

- client/components/sign-form.js
> fixed sign form

- client/components/products/allProducts.js
- client/components/products/productGrid.js
- client/components/products/productThumb.js
- client/components/products/singleProduct.js
- client/store/order.js
- server/api/users.js
add to cart functionality added for allproducts and single product views. currently only works for logged in user.
> Add to cart

- client/components/user-home.spec.js
- server/api/users.spec.js
- server/db/models/product.spec.js
- server/db/models/user.spec.js
Create initial working tests for Product Database Models. Nothing fancy. Tests we can create and delete.
> Working initial Product Test specs for Database Models

- client/components/sign-form.js
- client/components/user-home.js
- client/routes.js
- client/store/user.js
- script/seed.js
- server/api/users.js
Finished updating product images and descriptions. Reseed DB for changes. Working on user update form. May need help on Monday on that.
> finished pasta img/desc working on update form

- client/index.js
- server/index.js
> removed sockets

- client/components/orders/order-history.js
add fetch user before fetch orders. should eventually consider hoisting fetches to top.
> Order history

- client/store/product.js
- client/store/product.spec.js
- client/store/user.spec.js
Working basic test for Thunks in the Product Store Reducer
> Working Product Tests for Store Thunks

- client/components/products/product.spec.js
- client/components/products/productThumb.js
- client/components/products/singleProduct.js
Finally got productComponentTests working.
> Finally working productComponentTests

- client/components/index.js
- client/components/products/singleProduct.js
- client/store/order.js
- client/store/product.js
Silences stray front end console.logs and updated index.js imports for products
> Silenced front end Console Logs and updated index.js imports

- client/store/user.js
> fixed forwarding to all products after login

- client/components/orders/item-view.js
Set prices to dollar unites and calculated totals to 2 demical places for orders.
> Setprices to dollar units and 2 demical places in cart

- client/components/history.js
- client/components/index.js
- client/components/products/allProducts.js
- client/components/products/productGrid.js
- client/components/products/singleProduct.js
For notes- check Waffle issue 101.
> Fix user experience for "back button" for All products view with modal rendering. 

- script/seed.js
> remove carts from seed file

- client/components/aboutus.js
- client/components/sign-form.js
- client/routes.js
- client/store/about.js
- client/store/user.js
- server/api/users.js
Updated about page,  implemented duplicate userr error handling, updated user post route
> error handling added for users and style about us

- client/components/user-home.js
- server/db/models/user.js
Updated User Profile UI and fixed a sequelize model. Please reseed db before running
> fixed sequelize model and updated UI for user

- client/store/order.js
> fix items purchase price on checkout

- client/components/sign-form.js
- client/components/update-form.js
- client/components/user-home.js
- server/api/users.js
Updated everything to reflect changes for google sign in. Models, components, routes updated
> updated routes, models, and components for google sign in

- client/components/products/allProducts.js
- server/api/users.js
updated user put route for update form
> finished user put route for updating form

- client/components/products/allProducts.js
> fixed allproducts

- client/components/navbar.js
- public/style.css
Added styling on navbar. Shows current page the user is on by highlighting the button.
> finished styling navbar to show button/selected

- public/style.css
> button design

- client/components/sign-form.js
error handler updated. Still working on it
> error handler updated

- client/components/auth-form.js
- client/components/products/allProducts.js
- client/components/products/productThumb.js
- client/components/sign-form.js
> added yet more styling

- client/components/orders/cart-view.js
- client/components/orders/cart.js
- client/components/orders/checkout-form.js
- client/components/orders/item.js
- client/components/orders/order-history.js
- client/components/products/allProducts.js
- client/components/products/productThumb.js
- client/components/products/singleProduct.js
- client/components/sign-form.js
- client/store/index.js
- client/store/order.js
- package-lock.json
- package.json
- server/api/users.js
support for guests using local storage.
> Local store
